name: "Github Release"

on:
  push:
    branches:
      - master

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Android version
        id: versioning
        uses: ltDino/android-get-version-action@v1.0
        with:
          gradlePath: app/build.gradle.kts

      - name: Create Release Tag
        id: createReleaseTag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.versioning.outputs.versionName}}(${{ steps.versioning.outputs.versionCode}})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release Notes Formatted PR
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: ${{ steps.versioning.outputs.versionName}}(${{ steps.versioning.outputs.versionCode}})
          fromTag: lastestRelease
          configuration: ".github/workflows/configuration_github_release.json"

      - name: Update Lastest Release Tag
        id: updateLastest
        uses: richardsimko/update-tag@v1
        with:
          tag_name: lastestRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        run: |
          echo "${{ steps.github_release.outputs.changelog }}"

