name: "Github Release"

on:
  push:
    branches:
      - master

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Release Notes Commits
        id: commits
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: 1.4
          fromTag: 1.3
          commitMode: true

      - name: Build Release Notes Formatted PR
        id: prs
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: 1.4
          fromTag: 1.3
          configuration: "configuration_github_release.json"
      - name: Result Commit
        run: echo ${{ steps.commits.outputs.uncategorized_prs }}
      - name: Result PR
        run: echo ${{ steps.prs.outputs.uncategorized_prs }}
