name: "Github Release"

on:
  push:
    branches:
      - master
      - github_release_test

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: toshimaru/auto-author-assign@v1.4.0
      - name: Create Release Notes
        uses: mikepenz/release-changelog-builder-action@1.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}