name: "Github Release"

on:
  push:
    branches:
      - master

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Android version
        id: versioning
        uses: ltDino/android-get-version-action@v1.0
        with:
          gradlePath: app/build.gradle.kts

      - name: Get Lastest Release Tag
        id: tags
        run: |
          echo ::set-output name=prev::`git tag -l "[0-9]*[.][0-9]*([0-9]*)" --sort=-version:refname | head -n 1` name=new::${{ steps.versioning.outputs.versionName}}(${{ steps.versioning.outputs.versionCode}})

      - name: Create Release Tag
        id: createReleaseTag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.tags.outputs.new }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release Notes Formatted PR
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: ${{ steps.tags.outputs.new }}
          fromTag: ${{ steps.tags.outputs.prev }}
          configuration: ".github/workflows/configuration_github_release.json"

      - name: Log Release
        run: |
          echo "${{ steps.github_release.outputs.changelog }}"

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: $${{ steps.tags.outputs.new }}
          release_name: v ${{ steps.tags.outputs.new }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
