name: "Github Release"

on:
  push:
    branches:
      - master

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Android version
        id: versioning
        uses: ltDino/android-get-version-action@v1.0
        with:
          gradlePath: app/build.gradle.kts

      - name: Build Release Notes Formatted PR
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: 1.4
          fromTag: 1.3
          configuration: ".github/workflows/configuration_github_release.json"

      - name: Create Release
        run: |
          echo "The versionCode was ${{ steps.versioning.outputs.versionCode }}"
          echo "The versionName was ${{ steps.versioning.outputs.versionName }}"
