name: "Github Release"

on:
  push:
    branches:
      - master
      - github_release/*

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Release Notes Commits
        id: commits
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitMode: true

      - name: Build Release Notes Formatted PR
        id: prs
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: "configuration_github_release.json"
      - name: Result
        run: echo ${{ steps.prs.outputs.changelog }}
