name: "Github Release"

on:
  push:
    branches:
      - master
      - github_release_test/*

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Create Release Notes
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}