name: "Github Release2 test"

on:
  push:

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Android version
        id: versioning
        uses: ltDino/android-get-version-action@v1.0
        with:
          gradlePath: app/build.gradle.kts

      - name: Get Lastest Release Tag
        id: tags
        run: |
          echo ::set-output name=prev::`git tag -l "[0-9]*[.][0-9]*([0-9]*)" --sort=-version:refname | head -n 1` name=new::${{ steps.versioning.outputs.versionName}}(${{ steps.versioning.outputs.versionCode}})

      - name: Log Release
        run: |
          echo "${{ steps.github_release.outputs.prev }} ${{ steps.github_release.outputs.new }}"