name: "PreTag"

on:
  push:
    branches:
      - test

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0


      - name: Create Release
        run: |
          echo "${{ steps.previoustag.outputs }}"

