name: "PreTag"

on:
  push:
    branches:
      - test

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Previous tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Create Release
        run: |
          echo "${{ steps.tagName.outputs.tag }}"

